client/app/addPlant/browsePlantController.js
client/app/auth/authController.js
client/app/auth/loginView.html
client/app/auth/signupView.html
client/app/dashboard/dashboardController.js
client/app/dashboard/dashboardView.html
client/app/main.js
client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
client/app/plantProfile/plantProfileController.js
client/app/plantProfile/plantProfileView.html
client/app/services/services.js

[structure] added file skeleton to loginView.html	
[structure] added file skeleton to signupView.html	
[structure] added file skeleton to dashboardView.html	
[structure] added file skeleton to plantProfileView.html	
[structure] added file skeleton to myPlantsView.html	
[structure] deleted unecessary views from app directory	
[structure] added file skeleton for browsePlantController.js	
[structure] added file skeleton for authController.js	
[structure] added file skeleton for dashboardController.js	
[structure] added file skeleton for main.js
[structure] added file skeleton for myPlantsController.js	
[structure] added file skeleton for plantProfileController.js
[structure] added file skeleton for services.js

[structure] added file skeletons in app directory

---

client/app/addPlant/browsePlantController.js
server/config/middleware.js
server/db/helpers.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js
server/routes/users/usersHandler.js
server/routes/users/usersRoutes.js
server/server.js

[structure] added file skeleton to middleware.js	
[structure] added file skeleton to helpers.js	
[structure] added file skeleton to plantsHandler.js	
[structure] added file skeleton to usersRoutes.js	
[structure] added file skeleton to server.js	
[refactor] changed name of plantRoutes.js to plantsRoutes.js	
[refactor] changed name of userHandler.js to usersHandler.js	
[structure] removed unnecessary files from server directory

[structure] added file skeletons to server directory

---

package.json

[refactor] added bower to dependencies in package.json

[refactor] added bower to dependencies in package.json

---

client/app/main.js
client/index.html

[refactor] injected ui.router and fixed templateUrl path in main.js
[refactor] added script tags into index.html

[refactor] injected ui.router and fixed templateUrl path in client directory

---

server/db/sequelize.js

[structure] added tables to models in sequelize.js	
[refactor] established relationships and syncd schema in sequelize.js

[refactor] created schema models and relationships in sequelize.js

---

server/db/helpers.js

[structure] added file skeleton to helpers.js
[structure] wrote first query and stubbed out other queries in helpers.js

[structure] stubbed out queries/helper functions in helpers.js

---

server/db/helpers.js

[refactor] added helper functions to helpers.js

[refactor] added helper functions to helpers.js

---

server/db/helpers.js
server/db/sequelize.js

[refactor] added params to sequelize.js
[style] fixed indentation in helpers.js

[refactor] added params to sequelize.js

---

server/db/helpers.js

[refactor] added addPlantToGarden helper function to helpers.js

[refactor] added addPlantToGarden helper function to helpers.js

---

client/app/browsePlant/browsePlantController.js
client/app/services/services.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[refactor] added addPlant route and handler in plants directory
[structure] created addPlant function to scope in browsePlantControlller.js
[structure] added addPlant function to Plants factory in sevices.js
[refactor] modified addPlant route and handler in plants directory

[structure] added routing skeleton for addPlants on in client and server directories

---

server/db/helpers.js

[feat] added database helper functions to helpers.js

[feat] added database helper functions to helpers.js

---

client/app/main.js
client/app/myPlants/myPlantsController.js
client/app/services/services.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[structure] added getUserPlants to myPlantsController.js	
[refactor] added getUsersPlants to Plants factory in services.js	
[refactor] added stateparam to main.js	
[refactor] added getPlantsFOrAUser in plantsHandler.js	
[refactor] added loadPlants route in plantsRoutes.js

[refactor] created routing skeleton for getUserPlants in client and server directories

---

client/app/main.js
client/app/myPlants/myPlantsController.js
client/app/plantProfile/plantProfileController.js
client/app/services/services.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[refactor] added getUserPlants to to myPlantsController.js
[refactor] added getSpecieInfoOfPlant to scope in plantProfileController.js
[refactor] added plant functions to plant factory and made a ProfileInfo in services.js
[refactor] added getSpeiceInfo to plantsHandler.js	
[refactor] added loadSpecieInfo in plantsRoutes.js	
[refactor] changed plantProfile url in main.js

[refactor] added routing skeleton for getSpecie routing in client and server directories

---

client/app/auth/authController.js
client/app/services/services.js
server/routes/users/usersHandler.js
server/routes/users/usersRoutes.js

[refactor] added addUser route to usersRoutes.js
[refactor] added addUser function to usersHandler.js
[refactor] added addUser function to authController.js
[refactor] added Users factory to services.js

[refactor] added addUser routing skeleton to users directory

---

client/index.html

[style] Cleaned up variables and added comment in index.html

	[style] Cleaned up variables and added comment in index.html

---

client/app/auth/authController.js
client/app/auth/signupView.html
client/app/services/services.js

[refactor] added user object to authController.js
[refactor] added addUser function to services.js
[refactor] added form and submit to signupView.html
[refactor] added createUser function to authController.js

[refactor] added user authentication to client directory

---

client/app/main.js
client/app/plantProfile/plantProfileController.js
client/app/utility.js
client/assets/styles.css
client/index.html
server/db/helpers.js

[refactor] edit urlRouterProvider.otherwise in main.js
[style] edit period to correct styling error plantProfileController.js
[style] edit spacing in helpers.js
[refactor] add sidebar functionality in index.html

[refactor] add sidebar dropdown functionality to index.html

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html
client/app/main.js
client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
client/app/plantProfile/plantProfileController.js
client/app/services/services.js
server/db/helpers.js
server/db/sequelize.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[refactor] finished the getSpecieInfoOfPlant function in plantProfileController.js
[style] added a TODO comment in plantsHandler.js	
[structure] added rough function skeleton for scope.browse in browsePlantController.js	
[structure] added rough skeleton of view functionality in browsePlantView.html
[refactor] changed variable name in myPlantsController.js	
[refactor] added rough view skeleton for myPlantsView.html	
[refactor] changed variable name and invoked function in plantProfileController.js	
[refactor] added browsePlant and addPlant functionality in browsePlant directory	
[refactor] added fake data to ProfileInfo in services.js	
[refactor] worked on server side data handling in plants directory	
[refactor] changed variables in helpers.js	
[refactor] renamed a variable in …

[refactor] worked on plant routing in client and server directories 

---

client/app/browsePlant/browsePlantController.js
client/app/main.js
client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
client/app/plantProfile/plantProfileController.js
client/app/plantProfile/plantProfileView.html
client/app/services/services.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[refactor] added getPlant Handler and Route in plants directory	
[refactor] fixed some states in main.js	
[refactor] added getPlant to Plants factory in services.js	
[refactor] added getPlant function to scope in plantProfileController.js	
[refactor] added placeholder divs for data in plantProfileView.html
[refactor] added scope variables in browsePlantController.js	
[refactor] modified getUserPlants for controller and view myPlants directory

[refactor] worked on getPlant routing in client and server directories 

---

server/db/helpers.js

[refactor] edit table names to be plural in helpers.js

[refactor] edit table names to be plural in helpers.js

---

server/db/helpers.js
server/db/sequelize.js

[refactor] fixed tables in db directory

[refactor] fixed tables in db directory

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html
client/app/services/services.js
server/db/helpers.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[refactor] fixed functions functionality in browsePlantController.js	
[refactor] fixed view functionaility in browsePlantView.html	
[refactor] fixed handlers and routes in plants directory	
[refactor] changed variables in helpers.js	
[refactor] changed url in services.js

[refactor] fixed browsePlant routing in client and server directory

---

client/app/services/services.js

[refactor] add test profile to ProfileInfo factory in services.js

[refactor] add test profile to ProfileInfo factory in services.js

---

package.json
spec/specs.js

[test] Added to testing file in specs.js
[style] Reformatted to remove extra dependencies in package.json

[style] reformated package.json and updated specs.js

---

client/app/auth/authController.js
client/app/auth/signupView.html
client/app/services/services.js

[refactor] changed password type to text in signupView.html
[refactor] clear form on click in authController.js
[refactor] removed bug from services.js
[feat] injected Users factor in authController.js

[feat] connected view to database

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html
client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
client/app/services/services.js
server/db/helpers.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[refactor] added more functionality to browsePlant in view and controller in browsePlant directory
[refactor] added more functionality for browsePlantts page in plants directory
[refactor] added more functions to Plants factory in services.js	
[refactor] worked on browsePlant functionality in browerPlant diretory	
[refactor] worked on myPlants functionality in myPlants directory
[refactor] changed variables in services.js	
[refactor] changed some variable names in plantsHandler.js	
[refactor] fixed adding plant and garden functionality in browsePlant directory
[refactor] added return statement to getGardensFromUser in helpers.js	
[refactor] fixed addGarden handler in plantsHandler.js	
[refactor] made some changes in services.js

[refactor] worked on browsePlants functionality in client and server directory

---

client/app/auth/authController.js
client/app/auth/loginView.html
client/app/auth/signupView.html
client/app/main.js
client/app/services/services.js
client/index.html
package.json
server/routes/users/usersHandler.js

[feat] cleared form on view when button is clicked authController.js	
[feat] changed password type to text in signupView.html	
[feat] fix addUser to pass user object in services.js	
[refactor] removed console.log in usersHandler.js	
[refactor] added auth0 login and logout functions in authController.js	
[feat] added auth0 google calender login and logout in loginView.html	
[feat] added auth0 google calender login and logout in loginView.html	
[refactor] added auth initialize function and token retrieval on refr… …	
[refactor] removed getUser function from Users factory in services.js	
[refactor] added Auth0 scripts to index.html	
added Auth0 npm module to package.json

[feat] added google login with Auth0  in client directory

---

client/app/services/services.js
server/db/helpers.js
server/routes/plants/plantsHandler.js

[refactor] removed todo comments in services.js	
[refactor] fixed helper functions in helpers.js	
[refactor] fixed handler in plantsHanlder.js

[refactor] fixed getUsers Plants routes in client and server directories

---

client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
client/app/plantProfile/plantProfileController.js
client/app/services/services.js
server/db/helpers.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[refactor] worked on myPlants functionality in myPlants directory	
[refactor] added new handler and route in plants directory	
[refactor] added new getSpecieInfoById helper in helpers.js	
[refactor] worked on controller functionality in plantProfileController.js
[refactor] added getSpecieById in services.js

[refactor] worked on getting specieInfo by id in client and server directories 

---

client/app/dashboard/dashboardController.js
client/app/dashboard/dashboardView.html
client/app/main.js
client/assets/styles.css
client/index.html

[refactor] add logout route in main.js
[refactor] add hrefs for page redirects in index.html
[refactor] add css styling to dashboardView.html
[refactor] add data to view in dashboardView.html
[refactor] add functions for plant stats to dashboardController.js

[refactor] add functions for plant stats to dashboardController.js

---

.gitignore
client/app/auth/authController.js
client/app/dashboard/dashboardController.js
client/app/main.js
client/app/services/services.js
client/env/config.example.js
client/index.html

[structure] adding env directory for config variables to client directory
[refactor] add ignore env/config.js to .gitignore
[refactor] add script tag for env/config.js to index.html
[refactor] remove google api key and replace with variable for security in main.js
[fix] edit getPlantStats function in dashboardController.js
[style] edit missing semicolons in authController.js and services.js

[refactor] set config variables for api keys in client directory

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html
client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
client/app/plantProfile/plantProfileController.js
client/app/plantProfile/plantProfileView.html

[refactor] worked on myPlants functionality in myPlants directory	
[refactor] added functionality to plantProfileController.js	
[refactor] fixed linking between browsePlant and plantProfile in browsePlant directory
[refactor] fixed state changes in myPlants directory	
[refactor] built mvp garden filter in myPlants directory	
[refactor] added plant information in plantProfile directory	
[style] cleaned up console logs in myPlantsController.js

[refactor] worked on plant routing in client directory

---

client/app/browsePlant/browsePlantController.js
client/app/plantProfile/plantProfileController.js
client/app/plantProfile/plantProfileView.html
client/app/services/services.js

[refactor]added img tag in plantProfile.html	
[refactor] cleared out input fields after adding plant in browsePlantController.js
[style] cleaned up console logs in plantProfileController.js	
[style] cleaned up console.logs in services.js

[refactor] fixed plant views and controllers in client directory

---

client/app/auth/authController.js
client/app/auth/signupView.html
client/app/services/services.js
server/db/helpers.js
server/routes/users/usersHandler.js
server/routes/users/usersRoutes.js

[feat] added deleteUser function to authController.js
[feat] added button to call deleteUser in signupView.js
[feat] added deleteUser function to Users factory in services.js
[feat] added deleteUser function to helpers.js
[feat] added deleteUser function to usersHandler.js
[feat] added '/deleteUser' route to usersRoutes.js

[feat] added ability to delete user in client directory

---

client/app/auth/authController.js
client/app/auth/signupView.html
client/app/services/services.js
server/db/helpers.js
server/routes/users/usersHandler.js

[refactor] fixed data passed to deleteUser in authController.js
[refactor] changed form for delete user in signupView.html
[refactor] fixed data passed in to deleteUser in services.js
[refactor] fixed data passed in to deleteUser in helpers.js
[refactor] fixed data passed to deleteUser in usersHandler.js

[refactor] fixed deleteUser client and server directories

---

client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
client/app/services/services.js
server/db/helpers.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[refactor] added deletePlant function to myPlantsController.js
[refactor] added button and input to delete plant in myPlantsView.html
[refactor] added deletePlant function to services.js
[refactor] added delete user function to helpers.js
[refactor] added deletePlant function to plantsHandler.js
[refactor] added deletePlant route to plantsRoutes.js

[refactor] fixed delete plant functionality in client and server directories

---

client/app/myGarden/myGardenController.js
client/app/myGarden/myGardenView.html
client/app/myPlants/myPlantsView.html
client/app/services/services.js
server/db/helpers.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[feat] added deleteGarden to myGardenController.js
[feat] added delete garden input to myGardenView.html
[refactor] fixed spacing in myPlantsView.html
[feat] added deleteGarden to services.js
[feat] added deleteGarden to helpers.js
[feat] added deleteGarden to plantsHandler.js
[feat] added deleteGarden route to plantsRoutes.js

[feat] added deleteGarden functionality in client and server directories

---

client/app/browsePlant/browsePlantController.js

[refactor] added an alert in browsePlantController.js

[refactor] added an alert in browsePlantController.js

---

client/app/landingPage/landingPageView.html
client/assets/css/creative.css

[refactor] added sign in and log in buttons to landingPageView.html
[refactor] removed body font from creative.css

[refactor] added login/signup buttons to landingPageView.html in client directory

---

server/config/middleware.js

[refactor] added process env variable to middleware.js

[refactor] added process env variable to middleware.js

---

Procfile

[refactor] changed server in Procfile

[refactor] changed server in Procfile

---

client/app/dashboard/dashboardView.html
client/app/main.js
client/env/config.js

[refactor] remove ng-click bug in dashboardView.html
[refactor] remove repetitive code in main.js

[refactor] remove ng-click bug in dashboardView.html

---

server/config/middleware.js

[refactor] add if statement to check local or deployed status to middleware.js

[refactor] add if statement to check local or deployed status to middleware.js

---

client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html

[refactor] fixed delete Plants input and refresh in myPlants directory

[refactor] fixed delete Plants input and refresh in myPlants directory

---

client/index.html
server/config/middleware.js

[refactor] edit process.env.DEPLOYED variable in middleware.js
[refactor] remove font script tags in index.html

[refactor] edit process.env.DEPLOYED variable in middleware.js

---

client/app/services/services.js

[refactor] wrote getProfile and setProfile in services.js

[refactor] wrote getProfile and setProfile in services.js

---

client/app/landingPage/landingPageView.html
client/app/landingPage/signupView.html
client/assets/css/creative.css

[refactor] changed color in creative.css
[refactor] fixed merge conflict in landingPageView.html 
[refactor] removed contact and about links in landingPageView.html 
[refactor] removed contact and about links in landingPageView.html

[refactor] refactored css in client directory

---

client/app/navbar/navbarController.js
client/app/navbar/navbarView.html

[refactor] add ng-class for sidebar functionality to navbarView.html
[refactor] add toggleSideBar function to navbarController.js

[refactor] add ng-class for sidebar functionality to navbarView.html

---

client/app/landingPage/landingPageController.js
client/app/landingPage/userSettingsView.html
client/app/main.js
client/app/navbar/navbarView.html

[refactor] removed user location from landingPageController.js
[feat] added /settings route to main.js
[refactor] added settings link to navbar dropdown in navbarView.html
[feat] added userSettingView.html

[feat] added user settings view to client side

---

client/app/landingPage/landingPageController.js
client/app/services/services.js
server/db/helpers.js
server/routes/users/usersHandler.js
server/routes/users/usersRoutes.js

[refactor] added getUser in in users directory
[refactor] fixed getUser and addUser in helper.js	
[refactor] added database routes in landingPageController.js	
[refactor] added getUser to Users factory in services.js

[refactor] worked on login functionality in client and server directories

---

client/app/browsePlant/browsePlantController.js
client/app/dashboard/dashboardController.js
client/app/landingPage/landingPageController.js
client/app/myPlants/myPlantsController.js
client/app/navbar/navbarController.js
client/app/plantProfile/plantProfileController.js
client/app/services/services.js

[refactor] set username on localStorage in landingPageController.js	
[refactor] removed ProfileInfo factory from services.js	
[refactor] removed ProfileInfo and got username from localStorage in app directory

[refactor] removed ProfileInfo and got username from localStorage in app directory

---

client/app/dashboard/dashboardController.js

[refactor] edit typeOf error for getPlantStats in dashboardController.js
[refactor] remove console.logs in dashboardController.js

[refactor] edit typeOf error for getPlantStats function in dashboardController.js

---

client/app/landingPage/landingPageController.js

[refactor] changed sign in modal in landingPageController.js

[refactor] changed sign in modal in landingPageController.js

---

client/app/navbar/navbarView.html

[refactor] add css to profile photo and edit calendar button in navbarView.html

[refactor] add css to profile photo and edit calendar button in navbarView.html

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html

[refactor] added filter array to browsePlantController.js
[refactor] added filter functionality to browsePlantView.html

[refactor] added filter to browse plant on client side

---

client/app/browsePlant/browsePlantView.html
client/app/myGarden/myGardenController.js

[refactor] removed add garden in browsePlantView.html
[refactor] changed logic to add plant without garden in myGardenController.js

[refactor] removed add garden logic from client side

---

client/app/myGarden/myGardenController.js
client/app/myGarden/myGardenView.html
client/app/services/services.js
package.json
server/config/mailer.js
server/config/middleware.js
server/routes/events/eventsHandler.js
server/routes/events/eventsRoutes.js

[refactor] added google apidependencies in package.json	
[structure] added mailer.js file to config directory	
[refactor] added nodemailer to package.json	
[refactor] added nodemailer code setup in mailer.js	
[refactor] added eventRouting into middleware.js	
[structure] added events file skeleton to events directory in routes directory	
[refactor] added request handling to eventsHandler.js	
[refactor] added routes to eventRoutes.js	
[refactor] added postToGoogleCalendar route in eventsRoutes.js	
[refactor] added postToGoogleCalendar Handler to eventsHandler.js	
[refactor] added delete garden and its plants to myGardenController.js	
[refactor] added instructions and delete functionality in myGardenVie… …	
[refactor] deleted myGardenDirective.js from myGarden directory
[refactor] added …

[refactor] added garden functionality and event functionality in client and server directories

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html
client/assets/css/creative.css

[refactor] changed logic and plant array name in browsePlantController.js
[refactor] added button and panel view to browsePlantView.html
[refactor] removed button css from creative.css

[refactor] changed browsePlantView in client directory

---

server/db/helpers.js
spec/server/server.spec.js

[refactor] fixed console.logs in helpers.js	
[test] added plant testing to server.spec.js

[test] added plant testing to server.spec.js

---

client/app/myGarden/myGardenController.js

[refactor] Fixed bug that didn't update garden immediately in myGardenController.js

[refactor] Fixed bug that didn't update garden immediately in myGardenController.js

---

server/db/sequelize.js

[refactor] Switched database to postgress in sequelize.js

[refactor] Switched database to postgress in sequelize.js

---

spec/server/server.spec.js

[refactor] added 10 specs to test in server.spec.js

[refactor] added 10 specs to test in server.spec.js in server directory

---

client/app/myGarden/myGardenController.js
client/app/myGarden/myGardenView.html

[refactor] added time and AddPlantEvent functionality to myGardenController.js
[refactor] changed some view functionality in myGardenView.html

[refactor] added adPlantEvent functionality to myGarden directory

---

bower.json
client/app/myGarden/myGardenController.js
client/app/navbar/navbarView.html
client/index.html

[refactor] added findWaterTime to myGardenController.js
[bug] fix findWaterTime and formDate functions in myGardenController.js
[refactor] add moments script tag to index.html
[refactor] added moments library to bower.json
[refactor] remove profile-image class from navbarView.html

[refactor] added findWaterTime to myGardenController.js

---

client/app/landingPage/landingPageView.html
client/assets/css/styles.css

[refactor] removed merge conflict from landingPageView.html
[refactor] removed extra image css from styles.css

[feat] profile image css changed in client directory

---

client/app/browsePlant/browsePlantView.html
client/app/landingPage/landingPageView.html
client/app/myGarden/myGardenView.html
client/app/navbar/navbarView.html

[refactor] changed content of page in landingPageView.html
[refactor] changed instructions in myGardenView.html	
[refactor] changed names and order in navbarView.html	
[refactor] added instructions in browsePlant.html

[refactor] added instructions in app directory

---

client/app/myGarden/myGardenController.js

[refactor] remove getTime function in myGardenController.js

[refactor] remove getTime function in myGardenController.js

---

client/app/landingPage/landingPageView.html
client/app/navbar/navbarView.html
client/assets/css/styles.css

[refactor] moved sections in landingPageView.html
[refactor] changed organization of navbar in navbarView.html
[refactor] changed css affecting navbar in styles.css

[feat] navbar css and landing page changed in client directory

---

client/app/dashboard/dashboardController.js
client/app/landingPage/landingPageController.js
client/app/myGarden/myGardenController.js
server/config/mailer.js
server/db/sequelize.js
server/routes/events/eventsHandler.js

[refactor] re-added back Events schema into sequelize.js
[refactor] added the getEvents functionality in dashboardController.js	
[refactor] added tokens on localStorage in landingPageController.js	
[refactor] injected store into myGardenController.js	
[refactor] changed the mailOptions object in mailer.js	
[refactor] made changes to postToGoogleCalendar in eventsHandler.js

[refactor] worked on event and calendar routing in client and server directories

---

client/assets/css/styles.css

[refactor] changed color scheme in styles.css

[refactor] changed color scheme in styles.css on client side

---

client/app/myGarden/myGardenController.js

[refactor] added watering schedule information to myGardenController.js

[refactor] added watering schedule information to myGardenController.js

---

client/assets/css/styles.css

[refactor] changed navbar colors in styles.css

[refactor] changed navbar colors in styles.css

---

client/app/myGarden/myGardenController.js
server/routes/events/eventsHandler.js

[refactor] added waterschedule to DB in myGardenController.js
[refactor] fixed error message in eventsHandler.js

[refactor] worked on waterschedule events in client and server directories

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html
client/app/calendar/calendarController.js
client/app/calendar/calendarView.html
client/app/dashboard/dashboardView.html
client/app/directives/plantProfileDirective.js
client/app/main.js
client/app/myPlants/myPlantsView.html
client/index.html

[structure] added calendarView and calendarController to calendar directory
[refactor] added subSubView for calendarView in main.js
[refactor] added script tag for calendarController to index.html
[refactor] added ui-view for calendarView in dashboardView.html
[refactor] edit auto search feature in browsePlant directory
[structure] added directives directory
[refactor] added plantProfileDirective to module in main.js
[refactor] remove unwanted text from plantProfileDirective.js
[refactor] added profile directive to myPlantsView.html
[refactor] added plantProfileDirective script tag to index.html

[structure] added calendarView and calendarController to calendar directory

---

client/app/calendar/calendarController.js
spec/client/navbarController.spec.js

[test] added testing on scope variables in navbarController.spec.js
[test] added scope variable tests to navbarController.spec.js
[refactor] remove console.log from calendarController.js

[test] added testing on scope variables in navbarController.spec.js

---

client/app/dashboard/dashboardView.html
client/assets/css/styles.css

[refactor] fixed merge conflict in dashboardView.html
[refactor] changes navbar css in styles.css

[refactor] changed navbar and dashboard in client side

---

bower.json
client/app/calendar/calendarController.js
client/app/calendar/calendarView.html
client/app/main.js
client/index.html

[refactor] added events scope variable to calendarController.js
[refactor] added ui.calendar div in calendarView.html
[refactor] added angular-ui-calendar library to bower.json
[refactor] added ui.calendar dependency to module in main.js
[refactor] added angular-ui-calendar script tag to index.html

[refactor] added angular-ui-calendar library to bower.json

---

bower.json
client/app/calendar/calendarController.js
client/app/calendar/calendarView.html
client/app/main.js
client/index.html

[refactor] added ui-calendar to bower.json
[refactor] added test events to calendarController.js	
[refactor] worked on calendarView.html
[refactor] added ui bootstrap to main.js	
[refactor] added ui bootstrap to index.html

[refactor] worked on ui calendar in client directory

---

bower.json
package.json

[refactor] specify angular version in bower.json
[refactor] specify angular version in bower.json
[refactor] specify dependencies in package files

[refactor] specify angular version in bower.json

---

package.json
server/db/sequelize.js

[refactor] move devDependencies to dependencies in package.json
[refactor] remove postgresql connection in sequlize.js

[refactor] move devDependencies to dependencies in package.json

---

client/app/browsePlant/browsePlantView.html
client/app/dashboard/dashboardController.js
client/app/dashboard/dashboardView.html
client/app/navbar/navbarView.html
client/assets/css/creative.css
client/assets/css/styles.css

[refactor] changed header in browsePlantView.html
[refactor] added total plants to dashboardController.js
[refactor] changed statistics in dashboardView.html
[refactor] changed link names in navbarView.html
[refactor] changed hover color css in creative/css
[refactor] changed dashboard css in styles.css

[refactor] changed dashboard css and html in client directory

---

client/app/myGarden/myGardenController.js

[refactor] Resolved bugs around Deleting gardens in myGardenController.js

[refactor] Resolved bugs around Deleting gardens in myGardenController.js

---

server/db/sequelize.js
server/routes/events/eventsHandler.js

[refactor] remove postgreSQL from sequelize.js
[refactor] remove GOOGLE_CALENDAR_ID from eventsHandler.js
[refactor] edit schema in sequelize.js
[refactor] remove google calendar config variables in eventsHandler.js

[refactor] remove postgreSQL from sequelize.js

---

bower.json
client/app/calendar/calendarController.js
client/app/calendar/calendarView.html
client/app/dashboard/dashboardView.html
client/app/myGarden/myGardenController.js
client/app/services/services.js
client/index.html
server/db/helpers.js
server/routes/plants/plantsHandler.js
server/routes/plants/plantsRoutes.js

[refactor] added getEvents into calendarController.js
[refactor] added scope to calendarView.html
[refactor] added uiview into dashboardView.html	
[refactor] worked on addPlantEvent functionality in myGardenControlle… …	
[refactor] wrote getPlantById service in services.js	
[refactor] wrote getPlantById helper function in helpers.js	
[refactor] added getPlantById handler in plantsHandler.js	
[refactor] wrote loadPlantById in plantRoutes.js	
[refactor] fixed script tags in index.html
[refactor] added fullcalendar in bower.json

[refactor] worked on event handling in client and server directory

---

client/app/browsePlant/browsePlantController.js
client/app/landingPage/landingPageController.js
server/db/helpers.js
server/routes/plants/plantsHandler.js

[refactor] removed buggy functions from browsePlantController.js
[refactor] removed console logs from landingPageController.js
[refactor] fixed addPlant function in helpers.js
[refactor] fixed addPlants function in plantsHandler.js

[refactor] fixed errors in browsePlant in client/server directories

---

client/app/calendar/calendarController.js
client/app/calendar/calendarView.html
client/app/dashboard/dashboardView.html
client/assets/css/styles.css
client/index.html

[refactor] fixed angular-ui-calendar error in calendarController.js
[refactor] added html for angular-ui-calendar to calendarView.html
[refactor] remove h1 tag in dashboardView.html
[style] removed styling for dashboardView in styles.css
[refactor] added fullcalendar link tag in index.html

[refactor] fixed angular-ui-calendar error in calendarController.js

---

client/app/calendar/calendarController.js
client/app/myGarden/myGardenController.js
server/routes/events/eventsHandler.js

[refactor] added calendar functionality in calendarController.js	
[refactor] made changes to addPlantEvent in myGardenController.js	
[refactor] removed console.logs from eventsHandler.js

[refactor] added calendar functionality in client and server directories

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html

[refactor] added plant picture to browsePlantController.js
[refactor] added plant picture to browsePlantView.html

[refactor] added plant picture to browse plants in client directory

---

client/app/calendar/calendarController.js
client/app/myPlants/myPlantsController.js
client/app/services/services.js
server/db/helpers.js
server/routes/events/eventsHandler.js
server/routes/events/eventsRoutes.js

[refactor] added removeAllPlantEvents to helper.js	
[refactor] removed console.logs from calendarController.js	
[refacotor] fixed delete plants and events in myPlantsController.js	
[refactor] added removeAllPlantEvents in services.js
[refactor] added removeAllPlantEvents to eventsHandler.js	
[refactor] added removeAllPlantEvents route to eventsRoutes.js

[refactor] fixed delete plants and events functionality in server and client directories

---

client/app/calendar/calendarController.js

[refactor] fixed length of dates in calendarController.js	
[refactor] added plantName to calendar events in calendarController.js

[refactor] worked on calendar functionality in calendarController.js

---

client/app/dashboard/dashboardController.js
client/app/directives/plantProfileDirective.js
client/app/directives/profileDirectiveView.html
client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
client/app/plantProfile/plantProfileController.js
server/db/helpers.js

[refactor] remove spacing in dashboardController.js
[refactor] added profile directive functionality to plantProfileDirective.js
[refactor] added plantProfileDirective functionality to myPlantsController.js
[refactor] added profile tag and added panel for delete plant in myPlantsView.html
[refactor] edited getPlant function in plantProfileController.js
[refactor] edited getSpeciesInfoById helper function in helpers.js

[refactor] added profile directive functionality to plantProfileDirective.js

---

client/app/myGarden/myGardenController.js

[refactor] fixed deleting plants and events in myGardenController.js

[refactor] fixed deleting plants and events in myGardenController.js

---

client/app/landingPage/landingPageView.html
client/app/myPlants/myPlantsController.js

[refactor] edited fruits image file path in landPageView.html
[refactor] added comma to controller dependencies to myPlantsController.js

[refactor] edited fruits image file path in landPageView.html

---

client/app/myGarden/myGardenController.js

[refactor] fixed idOf Species in myGardenController.js

[refactor] fixed idOf Species in myGardenController.js

---

client/app/calendar/calendarController.js
server/config/mailer.js
server/routes/events/eventsHandler.js
server/routes/users/usersHandler.js

[refactor] took out names in calendar in calendarController.js	
[refactor] reworked addUser in mailer.js	
[refactor] cleaned up some code in eventsHandler.js	
[refactor] fixed emailing in addUser usersHandler.js

[refactor] fixed addUser in client and server directories

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html
client/app/dashboard/dashboardView.html
client/app/navbar/navbarView.html
client/assets/css/styles.css

[refactor] changed styling for dashboard in styles.css
[refactor] moved navbar slider out of navbarView.html
[refactor] moved navbar slider into dashboardView.html
[refactor] removed unnecessary function from browsePlantController.js
[refactor] changed page title in browsePlantView.html

[feat] changed css and html in client directory

---

client/app/browsePlant/browsePlantView.html
client/app/myGarden/myGardenView.html
client/app/myPlants/myPlantsView.html

[refactor] added navbar slider to browsePlantView.html
[refactor] added navbar slider to myGardenView.html
[refactor] added navbar slider to myPlantsView.html

[feat] added navbar slider to all views in client directory

---

client/app/calendar/calendarController.js
server/db/helpers.js
server/routes/events/eventsHandler.js
server/routes/plants/plantsHandler.js

[refactor] made calendar events faster in calendarController.js	
[refactor] removed console.logs in helpers.js	
[refactor] transfered getEvents for a user to server side in eventsHadler.js
[refactor] took out console.logs in plantsHandler.js

[refactor] made calendarEvents faster in client and server directories

---

client/app/myGarden/myGardenController.js
client/app/myGarden/myGardenView.html
client/app/services/services.js
server/routes/events/eventsHandler.js
server/routes/events/eventsRoutes.js

[refactor] took out prompts and confirms and defaulted 100 in myGardenController.js
[refactor] put back in class in myGardenView.html	
[refactor] changed postToGoogleCalendar in services.js	
[refactor] changed postToGoogleCalendar in eventsHandler.js	
[refactor] changed postToGoogleCalendar in eventsRoutes.js

[refactor] fixed route names in client and server directories

---

client/app/browsePlant/browsePlantView.html
client/app/dashboard/dashboardView.html
client/app/myPlants/myPlantsView.html
client/app/plantProfile/plantProfileView.html
client/assets/css/styles.css

[refactor] changed layout in myPlantsView.html
[refactor] UI changes in browsePlantView.html
[refactor] UI changes in dashboardView.html
[refactor] moved navbar slider in plantProfileView.html
[refactor] added css in styles.css

[refactor] moved navbar slider in client directory

---

client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
server/db/helpers.js

[refactor] took out delete plant and events in myPlantsController.js
[refactor] took out some console.logs in helpers.js
[refactor] resolved merge conflict in myPlantsView.html

[refactor] took out delete plant in server and client directories

---

client/app/myGarden/myGardenView.html
client/assets/css/creative.css

[refactor] changed layout in myGardenView.html
[refactor] changed success button css in creative.css

[refactor] changed myGarden css and layout in client directory

---

client/app/landingPage/landingPageView.html
client/assets/css/styles.css

[refactor] changed panel and image css in styles.css
[refactor] changed logo to white in landingPageView.html
[refactor] removed logo css in styles.css

[refactor] changed logo html and css in client directory

---

client/index.html

[refactor] moved order of stylesheets for ionicons in index.html

[refactor] moved order of stylesheets for ionicons in index.html

---

bower.json
client/app/dashboard/dashboardView.html

[refactor] edit ionicons dependency in bower.json
[refactor] edit ionicons in dashboardView.html

[refactor] edit ionicons dependency in bower.json

---

client/app/landingPage/landingPageView.html

[refactor] changed brandon's bio on landingPageView.html

[refactor] changed brandon's bio on landingPageView.html in client directory

---

client/app/services/services.js
server/config/mailer.js
server/config/middleware.js
server/db/helpers.js
server/db/sequelize.js
server/routes/events/eventsHandler.js
server/routes/plants/plantsHandler.js

[refactor] removed console.logs in services.js	
[refactor] cleaned up code in mailer.js	
[refactor] cleaned up code in middleware.js	
[refactor] cleaned up console.logs in helpers.js	
[refactor] cleaned up code in sequelize.js
[refactor] cleaned up code in eventsHandler.js	
[refactor] cleaned up code in plantsHandler.js

[refactor] cleaned up code in server directory

---

karma.conf.js
spec/client/browsePlantController.spec.js
spec/client/navbarController.spec.js

[refactor] added angular-ui-calendar to files in karma.config.js
[refactor] removed extra injector in navbarController.spec.js
[refactor] rewrite browsePlantController spec and test all scope variables in browsePlantController.spec.js

[refactor] refactor client spec in browsePlantController.spec.js

---

client/app/browsePlant/browsePlantController.js
client/app/browsePlant/browsePlantView.html
client/app/calendar/calendarController.js
client/app/calendar/calendarView.html
client/app/dashboard/dashboardController.js
client/app/dashboard/dashboardView.html
client/app/directives/plantProfileDirective.js
client/app/directives/profileDirectiveView.html
client/app/landingPage/landingPageView.html
client/app/landingPage/userSettingsView.html
client/app/main.js
client/app/myGarden/myGardenController.js
client/app/myGarden/myGardenView.html
client/app/myPlants/myPlantsController.js
client/app/myPlants/myPlantsView.html
client/app/navbar/navbarController.js
client/app/navbar/navbarView.html
client/app/plantProfile/plantProfileController.js
client/app/plantProfile/plantProfileView.html
client/app/services/services.js
client/index.html
server/db/helpers.js

[style] cleaned up code format in browsePlantController.js
[style] cleaned up code in browsePlantView.html
[refactor] removed console.log in browsePlantController.js	
[refactor] removed unncessary variables and console logs in calendarC… …	
[style] cleaned up code in calendarView.html	
[style] cleaned up style in dashboardController.js	
[style] cleaned up quotes in dashboardView.html	
[style] cleaned up style in plantProfileDirective.js
[style] cleaned up quotes in profileDirectiveView.html	
[style] cleaned up comments in landingPageView.html
[style] cleaned up style in userSettingsView.html	
[style] cleaned up code in myGardenController.js	
[style] cleaned up code in myGardenView.html
[style] cleaned up code in myPlantsController.js	
[style] cleaned up code in myPlantsView.html	
[style] …

[style] cleaned up code for client and server directories
